# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trade-sleep-tg-bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_68234e70da954218a954b3c876358a1b }}/lokivklokenaandoke/trade-sleep-tg-bot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'trade-sleep-tg-bot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3333655135cc4312923826913912e87f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_68234e70da954218a954b3c876358a1b }}/lokivklokenaandoke/trade-sleep-tg-bot:${{ github.sha }}'